// ⚠️ IMPORTANT: This file is auto-generated by FlutterFire CLI.
// Run: flutterfire configure
// This will replace this file with your actual Firebase project settings.
// See SETUP_GUIDE.md for full instructions.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️ REPLACE THESE WITH YOUR ACTUAL VALUES FROM FIREBASE CONSOLE

  // Web configuration – uses the same project.
  // If you registered a separate web app in Firebase Console, update appId & apiKey.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5sv9z8C14feT1aRBFGE8OlC5aeLbBGuE',
    appId: '1:39005807333:web:418c98dbdc185451fc2a0c',
    messagingSenderId: '39005807333',
    projectId: 'bookmyturf-59d1f',
    storageBucket: 'bookmyturf-59d1f.firebasestorage.app',
    authDomain: 'bookmyturf-59d1f.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5sv9z8C14feT1aRBFGE8OlC5aeLbBGuE',
    appId: '1:39005807333:android:418c98dbdc185451fc2a0c',
    messagingSenderId: '39005807333',
    projectId: 'bookmyturf-59d1f',
    storageBucket: 'bookmyturf-59d1f.firebasestorage.app',
  );

  // After running `flutterfire configure`, this file will be auto-filled.

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.bookmyturf.app',
  );
}
